# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 153)
        Form.setMinimumSize(QtCore.QSize(330, 153))
        Form.setMaximumSize(QtCore.QSize(330, 153))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_group = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_group.sizePolicy().hasHeightForWidth())
        self.button_group.setSizePolicy(sizePolicy)
        self.button_group.setMinimumSize(QtCore.QSize(312, 135))
        self.button_group.setMaximumSize(QtCore.QSize(312, 135))
        self.button_group.setObjectName("button_group")
        self.layout = QtWidgets.QHBoxLayout(self.button_group)
        self.layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.layout.setObjectName("layout")
        self.from_cap = QtWidgets.QPushButton(self.button_group)
        self.from_cap.setEnabled(True)
        self.from_cap.setMinimumSize(QtCore.QSize(124, 40))
        self.from_cap.setMaximumSize(QtCore.QSize(124, 40))
        self.from_cap.setDefault(True)
        self.from_cap.setObjectName("from_cap")
        self.layout.addWidget(self.from_cap)
        self.from_file = QtWidgets.QPushButton(self.button_group)
        self.from_file.setEnabled(True)
        self.from_file.setMinimumSize(QtCore.QSize(123, 40))
        self.from_file.setMaximumSize(QtCore.QSize(123, 40))
        self.from_file.setAutoDefault(False)
        self.from_file.setDefault(True)
        self.from_file.setObjectName("from_file")
        self.layout.addWidget(self.from_file)
        self.horizontalLayout.addWidget(self.button_group)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "视频采集"))
        self.button_group.setTitle(_translate("Form", "选择视频采集方式"))
        self.from_cap.setText(_translate("Form", "摄像头"))
        self.from_file.setText(_translate("Form", "文件"))
